name: Release
options:
  bundleIdPrefix: com.jatraMaya
  settings:
    iOS:
      TARGETED_DEVICE_FAMILY: "1"  # 1 for iPhone, 2 for iPad
targets:
  Release!:
    type: application
    platform: iOS
    deploymentTarget: "16.4"
    sources:
      - Release
    info:
      path: App/Info.plist
      properties:
        UILaunchScreen: LaunchScreen
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
    dependencies:
      - package: HorizonCalendar
      - package: FSCalendar
packages:
  HorizonCalendar:
    url: https://github.com/airbnb/HorizonCalendar
    majorVersion: 1.16.0
  FSCalendar:
    url: https://github.com/WenchaoD/FSCalendar
    majorVersion: 2.8.3
